### ISSUE TITLE
Publish 0.3 to crates.io?

### ISSUE THREAD

**Issue by uberFoo** [hashmismatch/packed_struct.rs#34]
I just ran into the `PrimitiveEnum_u16` bug, and noticed that it was recently fixed, and the version bumped. Crates.io however doesn't yet contain the new version.

I've tried to clone your repo, and point `Cargo.toml` at it, but I don't yet know the proper magic to make it work. `cargo` sees the dependencies between `packed_struct` and `packed_struct_codegen` and insists on resolving them using Crates.io, which still contains the old versions. I'm sure that there's an incantation that could be invoked in `Cargo.toml` to make it comply, but I haven't landed on the exact permutation of `[patch]` sections yet.

If you were planning to publish soon (maybe an oversight?) then I could stop fighting with `cargo`.  :)

**Comment by rudib** [comment]
Just haven't had the time to release it, that's all. I'll try to push it out this evening.

In the meantime, try this:

```toml
[dependencies]
packed_struct = "0.3"
packed_struct_codegen = "0.3"

[patch.crates-io]
packed_struct = { git="https://github.com/hashmismatch/packed_struct.rs" }
packed_struct_codegen = { git="https://github.com/hashmismatch/packed_struct.rs" }
```

`cargo update` and you should be good to go.
